name: measure build artifacts
on:
  create:
    branches:
      - 'release/*'
  workflow_dispatch:

permissions:
  attestations: write
  contents: read
  id-token: write
    
jobs:
  call-workflow-passing-data:
    uses: maceip/encumbrance-rs/.github/workflows/gramine-attestion.yml@main
    secrets: inherit
    
